import * as firebase from 'firebase/app';

export const StubFirebaseUser: firebase.User = {
  'uid': 'PjO04UWv87NAvQ7D4cBT8hXOHrY2',
  'displayName': 'Nacho Data',
  'photoURL': 'https://pixabay.com/get/ee36b00721fc1c22d9584518a33219c8b66ae3d01db1194596f7c37a/cocktails-731898_1920.jpg',
  'email': 'nacho.data@gmail.com',
  'emailVerified': true,
  'phoneNumber': null,
  'isAnonymous': false,
  'providerData': [{
    'uid': '114756674506094847444',
    'displayName': 'Nacho Data',
    'photoURL': 'https://pixabay.com/get/ee36b00721fc1c22d9584518a33219c8b66ae3d01db1194596f7c37a/cocktails-731898_1920.jpg',
    'email': 'nacho.data@gmail.com',
    'phoneNumber': null,
    'providerId': 'google.com'
  }],
  'delete': null,
  'getIdToken': null,
  'getIdTokenResult': null,
  'linkWithCredential': null,
  'linkWithPhoneNumber': null,
  'linkWithPopup': null,
  'linkWithRedirect': null,
  'linkAndRetrieveDataWithCredential': null,
  'metadata': null,
  'reauthenticateAndRetrieveDataWithCredential': null,
  'reauthenticateWithCredential': null,
  'reauthenticateWithPhoneNumber': null,
  'reauthenticateWithPopup': null,
  'reauthenticateWithRedirect': null,
  'refreshToken': null,
  'reload': null,
  'sendEmailVerification': null,
  'toJSON': null,
  'unlink': null,
  'updateEmail': null,
  'updatePassword': null,
  'updatePhoneNumber': null,
  'updateProfile': null,
  'providerId': null,
};
